### ISSUE TITLE
Rework Watch-Directory to avoid Get-Event issues

### ISSUE THREAD

**Issue by nightroman** [nightroman/PowerShelf#4]
It turns out `Get-Event` has issues. With many fast changes in the watched
directory it may fail with an error "Collection was modified; enumeration
operation may not execute." and the stack:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.PowerShell.Commands.GetEventCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
```

The behaviour changed in PowerShell v5, hopefully it was fixed. But `Get-Event` should be avoided, v2-v4 are still in use.

`Watch-Directory` will be reworked using some inline C# code. This is not so
neat but it should work without issues and presumably more effectively.

**Comment by nightroman** [comment]
Some tests about `Get-Event` issues:
https://github.com/nightroman/PowerShellTraps/tree/master/Cmdlets/Get-Event/v2-4-Erratic-failure
